### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by pawelrutkowski** [lilskywalkr/KanapkaMan#7]
## To read
- [ ] Nuxt get started: https://nuxt.com/docs/getting-started/introduction
  - [ ] Introduction
  - [ ] Installation
  - [ ] Configuration
  - [ ] Views
  - [ ] Assets
  - [ ] Styling
  - [ ] Routing
  - [ ] SEO and Meta
  - [ ] Transitions
  - [ ] Data fetching
  - [ ] State Management
  - [ ] Error Handling
  - [ ] Server
  - [ ] Layers
  - [ ] Deployment
  - [ ] Testing
  - [ ] Upgrade Guide
- [ ] Nuxt guide: https://nuxt.com/docs/guide
  - [ ] Key contcepts
    - [ ] Auto-imports
    - [ ] Vue.js Development
    - [ ] Rendering Modes
    - [ ] Server Engine
    - [ ] Modules
    - [ ] ES Modules
    - [ ] TypeScript
  - [ ] DIrectory structure
    - [ ] .nuxt
    - [ ] .output
    - [ ] assets
    - [ ] components
    - [ ] composables
    - [ ] content
    - [ ] layouts
    - [ ] middleware
    - [ ] modules
    - [ ] node_modules
    - [ ] pages
    - [ ] plugins
    - [ ] public
    - [ ] server
    - [ ] utils
    - [ ] .env
    - [ ] .gitignore
    - [ ] .nuxtignore
    - [ ] app.config.ts
    - [ ] app.vue
    - [ ] nuxt.config.ts
    - [ ] package.json
    - [ ] tsconfig.json
- [ ] I18n https://i18n.nuxtjs.org/
- [ ] PWA https://vite-pwa-org.netlify.app/frameworks/nuxt

## Todo
- [ ] check firebase functions to get blog posts
- [ ] check firebase functions to get blog post article
- [ ] check firebase functions to send contact form
- [ ] create correct pwa config - `pwa.ts`
- [ ] instead of `moment` start using default js date
- [ ] divide i18n value with html to separated keys - do not use v-html, in translations should be only text, html tags should be in template section
- [ ] check website language with default language other than pl
- [ ] reduce using `any` type
- [ ] on website click on logo at bottom center of the page - 'nuxt dev tools' > select open graph > select code snippet > copy and paste with good config useSeoMeta and useHead
- [ ] clean up project - remove unused comments
